# Generated by Django 4.2.6 on 2023-11-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
